### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide   terms = (f_obs_float - f_exp)**2 / f_exp

### ISSUE THREAD

**Issue by jojo-Li-YZ** [elonganrochester/ADATscan#2]
When I was scripting the sample data, I found that the resulting files were inconsistent with the sample results.

python: 3.12

**RUN:**
$ python ADATscan_generalized.py seqs_AAA_AAG_example.fasta model.csv results.csv gene_body.csv 
Input codon of interest, if complete then type: 'n'n
Which multiple test correction will be run? (Bonferroni (B) or Benjamani-hochberg (BH))BH
What FDR will be used? (ex. 0.1)0.01
[]
.../miniconda3/envs/tRNA/lib/python3.12/site-packages/scipy/stats/_stats_py.py:8064: RuntimeWarning: invalid value encountered in divide
  terms = (f_obs_float - f_exp)**2 / f_exp

**Comment by jojo-Li-YZ** [comment]
The codon of interest was added .

**RUN:**
$ python ADATscan_generalized.py seqs_AAA_AAG_example.fasta model.csv results.csv gene_body.csv
Input codon of interest, if complete then type: 'n'aaa
Input codon of interest, if complete then type: 'n'n
Which multiple test correction will be run? (Bonferroni (B) or Benjamani-hochberg (BH))bh
What FDR will be used? (ex. 0.1)0.01
['K']
Traceback (most recent call last):
    x = (chisquare(chisquareobs, f_exp=chisquareexp))
  File "C:\Users\17792\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\stats\_stats_py.py", line 8254, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "C:\Users\17792\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\stats\_stats_py.py", line 8051, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are: 
0.32142857142857145
